name: Containse Build Check
on: pull_request
jobs:
  build_and_run_containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare local env
        run: touch sr-back/.env.local
      - name: Build and run containers
        run: (docker compose -f docker/docker-compose.yaml up --build --wait --wait-timeout=3 && exit 0) || (docker compose -f docker/docker-compose.yaml logs && exit 1)
      - name: Stop containers
        run: docker compose -f docker/docker-compose.yaml down
